# frozen_string_literal: true

# Cookbook:: wazuh_manager
# Recipe:: passwords
# Author:: Wazuh <info@wazuh.com>
#
# This recipe updates the Wazuh Manager's indexer credentials in the keystore.
# Run this after wazuh_indexer::passwords to update the manager with new passwords.
#
# Usage:
#   1. Run wazuh_indexer::passwords first to change indexer passwords
#   2. Set the new password in node['wazuh_manager']['indexer']['password']
#   3. Include this recipe to update the manager's keystore

admin_username = node['wazuh_manager']['indexer']['username']
admin_password = node['wazuh_manager']['indexer']['password']
passwords_file = node['wazuh_manager']['indexer']['passwords_file'] || '/root/wazuh-passwords.txt'

# Check if password is available from run_state, passwords file, or attributes
ruby_block 'get_indexer_password_from_run_state' do
  block do
    require 'json'

    password_found = false

    # Priority 1: Check run_state (same Chef run as indexer password change)
    if node.run_state['wazuh_indexer_admin_password']
      node.run_state['manager_indexer_password'] = node.run_state['wazuh_indexer_admin_password']
      Chef::Log.info('Using admin password from wazuh_indexer::passwords run_state')
      password_found = true
    elsif node.run_state['wazuh_passwords'] && node.run_state['wazuh_passwords']['admin']
      node.run_state['manager_indexer_password'] = node.run_state['wazuh_passwords']['admin']
      Chef::Log.info('Using admin password from wazuh_passwords run_state')
      password_found = true
    end

    # Priority 2: Read from passwords file (separate Chef run)
    if !password_found && ::File.exist?(passwords_file)
      begin
        passwords_data = JSON.parse(::File.read(passwords_file))
        if passwords_data['passwords'] && passwords_data['passwords']['admin']
          node.run_state['manager_indexer_password'] = passwords_data['passwords']['admin']
          Chef::Log.info("Using admin password from #{passwords_file}")
          password_found = true
        end
      rescue JSON::ParserError => e
        Chef::Log.warn("Failed to parse passwords file #{passwords_file}: #{e.message}")
      end
    end

    # Priority 3: Use node attributes (explicitly configured)
    if !password_found && admin_password && admin_password != 'admin'
      node.run_state['manager_indexer_password'] = admin_password
      Chef::Log.info('Using admin password from node attributes')
      password_found = true
    end

    # No fallback to default - fail explicitly if no password found
    unless password_found
      raise "No admin password found for indexer connection! Either:\n" \
            "  1. Run wazuh_indexer::passwords in the same Chef run, or\n" \
            "  2. Ensure #{passwords_file} exists with valid JSON (generated by wazuh_indexer::passwords), or\n" \
            "  3. Set node['wazuh_manager']['indexer']['password'] attribute (not 'admin')\n" \
            "Note: You can customize the passwords file path via node['wazuh_manager']['indexer']['passwords_file']"
    end
  end
  action :run
end

# Update the indexer username in wazuh-keystore
execute 'update_indexer_username' do
  command "/var/ossec/bin/wazuh-keystore -f indexer -k username -v #{admin_username}"
  action :run
  sensitive true
end

# Update the indexer password in wazuh-keystore
ruby_block 'update_indexer_password' do
  block do
    password = node.run_state['manager_indexer_password']
    system("/var/ossec/bin/wazuh-keystore -f indexer -k password -v '#{password}'")
    Chef::Log.info('Updated indexer password in wazuh-keystore')
  end
  action :run
  sensitive true
end

# Restart the manager to apply new credentials
service 'wazuh-manager' do
  action :restart
  only_if { ::File.exist?('/var/ossec/bin/wazuh-control') }
end

log 'manager_password_update_complete' do
  message <<~MSG
    ============================================================================
    Wazuh Manager indexer credentials updated in keystore.
    The wazuh-manager service has been restarted to apply the changes.
    ============================================================================
  MSG
  level :info
end
